import { z } from "zod";
import { str, Optional, Field, int, object, enums } from "@/lib/zod/helpers";
import { CommonEntity } from "@/schemas/common/types";

const NO_WHITESPACE = /^\S+$/;

export const MenuSchema = object({
  menu_id: Field({ min_length: 1, max_length: 20, pattern: NO_WHITESPACE }).str(),
  menu_nm: str().max(200),
  menu_level: int(),
  sort_ordr: int(),
  upper_menu_id: Optional(str().max(20)),
  url: Optional(str().max(400)),
  use_at: enums(["Y", "N"]),
  icon: Optional(str().max(50)),
});

export const MenuCreateInSchema = MenuSchema;
export const MenuUpdateInSchema = MenuSchema.omit({ menu_id: true });

export type Menu = z.infer<typeof MenuSchema>;
export type MenuOut = Menu & CommonEntity & { ParentGroup?: string; is_protected?: boolean };

export interface MenusOut {
  items: MenuOut[];
  total_count: number;
}

export interface MenuParentOptionOut {
  value: string;
  label: string;
  use_at: string;
}

export const DX_ICONS = [
  "accountbox",
  "activefolder",
  "add",
  "addtableheader",
  "airplane",
  "aligncenter",
  "alignjustify",
  "alignleft",
  "alignright",
  "arrowback",
  "arrowdown",
  "arrowleft",
  "arrowright",
  "arrowup",
  "attach",
  "back",
  "background",
  "bell",
  "belloutline",
  "blockquote",
  "bmpfile",
  "bold",
  "bookmark",
  "box",
  "bulletlist",
  "car",
  "card",
  "cart",
  "cellproperties",
  "chart",
  "chat",
  "check",
  "checklist",
  "chevrondoubleleft",
  "chevrondoubleright",
  "chevrondown",
  "chevronleft",
  "chevronnext",
  "chevronprev",
  "chevronright",
  "chevronup",
  "clear",
  "clearcircle",
  "clearformat",
  "clearsquare",
  "clock",
  "close",
  "codeblock",
  "coffee",
  "collapse",
  "color",
  "columnchooser",
  "columnfield",
  "columnproperties",
  "comment",
  "contains",
  "contentlayout",
  "copy",
  "cut",
  "dataarea",
  "datafield",
  "datapie",
  "datatrending",
  "datausage",
  "decreaseindent",
  "decreaselinespacing",
  "deletecolumn",
  "deleterow",
  "deletetable",
  "description",
  "detailslayout",
  "doc",
  "docfile",
  "docxfile",
  "doesnotcontain",
  "download",
  "dragvertical",
  "edit",
  "edittableheader",
  "email",
  "endswith",
  "equal",
  "errorcircle",
  "event",
  "eventall",
  "expand",
  "expandform",
  "export",
  "exportpdf",
  "exportselected",
  "exportxlsx",
  "eyeclose",
  "eyeopen",
  "favorites",
  "fieldchooser",
  "fields",
  "file",
  "fill",
  "filter",
  "find",
  "fixcolumn",
  "fixcolumnleft",
  "fixcolumnright",
  "floppy",
  "folder",
  "font",
  "fontsize",
  "food",
  "formula",
  "fullscreen",
  "gift",
  "globe",
  "greater",
  "greaterorequal",
  "group",
  "growfont",
  "handlehorizontal",
  "handlevertical",
  "header",
  "help",
  "hidepanel",
  "hierarchy",
  "home",
  "image",
  "imgarlock",
  "imgarunlock",
  "import",
  "importselected",
  "inactivefolder",
  "increaseindent",
  "increaselinespacing",
  "indent",
  "indeterminatestate",
  "info",
  "insertcolumnleft",
  "insertcolumnright",
  "insertrowabove",
  "insertrowbelow",
  "inserttable",
  "isblank",
  "isnotblank",
  "italic",
  "jpgfile",
  "key",
  "less",
  "lessorequal",
  "like",
  "link",
  "lock",
  "login",
  "map",
  "mediumiconslayout",
  "mention",
  "menu",
  "mergecells",
  "message",
  "minus",
  "money",
  "moon",
  "more",
  "movetofolder",
  "music",
  "newfolder",
  "notequal",
  "optionsgear",
  "orderedlist",
  "ordersbox",
  "overflow",
  "palette",
  "panelleft",
  "panelright",
  "parentfolder",
  "paste",
  "pasteplaintext",
  "pdffile",
  "percent",
  "photo",
  "photooutline",
  "pin",
  "pinleft",
  "pinmap",
  "pinright",
  "plus",
  "pptfile",
  "pptxfile",
  "preferences",
  "print",
  "product",
  "pulldown",
  "range",
  "redo",
  "refresh",
  "remove",
  "rename",
  "repeat",
  "return",
  "revert",
  "rowfield",
  "rowproperties",
  "rtffile",
  "runner",
  "save",
  "search",
  "selectall",
  "send",
  "sendfilled",
  "share",
  "showpanel",
  "shrinkfont",
  "smalliconslayout",
  "sortdown",
  "sortdowntext",
  "sorted",
  "sortup",
  "sortuptext",
  "spindown",
  "spinleft",
  "spinnext",
  "spinprev",
  "spinright",
  "spinup",
  "splitcells",
  "square",
  "startswith",
  "stickcolumn",
  "strike",
  "subscript",
  "sun",
  "superscript",
  "svgfile",
  "tableproperties",
  "tags",
  "taskcomplete",
  "taskhelpneeded",
  "taskinprogress",
  "taskrejected",
  "taskstop",
  "tel",
  "textdocument",
  "tips",
  "to",
  "todo",
  "toolbox",
  "trash",
  "triangledown",
  "triangleleft",
  "triangleright",
  "triangleup",
  "txtfile",
  "underline",
  "undo",
  "unfixcolumn",
  "unlock",
  "unpin",
  "unselectall",
  "upload",
  "user",
  "variable",
  "verticalalignbottom",
  "verticalaligncenter",
  "verticalaligntop",
  "video",
  "warning",
  "xlsfile",
  "xlsxfile",
] as const;
